tambahan baru

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -137,6 +137,21 @@ jobs:
           script: |
             ln -sf ${{ env.DIR_RELEASES }}/${{ env.DIR_SOURCE }} ${{ env.DIR_TARGET_CWD}}/current
 
+      - name: reload app
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ secrets.VPS_HOST }}
+          username: ${{ secrets.VPS_USER }}
+          key: ${{ secrets.VPS_KEY }}
+          script: |
+            ECOSYSTEM_FILE="${{ env.DIR_TARGET_CWD }}/ecosystem.config.json"
+            if [[ ! -f "$ECOSYSTEM_FILE" ]]; then
+              echo "Error: Ecosystem file not found at $ECOSYSTEM_FILE"
+              exit 1
+            fi
+            pm2 reload ${{ env.DIR_TARGET_CWD }}/ecosystem.config.json || pm2 start ${{ env.DIR_TARGET_CWD }}/ecosystem.config.json
+            pm2 save
+
       - name: send log
         run: |
           bun notif --data ${{ env.WIBU_DATA }} --log
