tambahan baru

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -51,27 +51,36 @@ jobs:
       # WIBU_DATE
       - name: init data
         run: |
-          echo "init data ..." | bun notif --data ${{ env.WIBU_DATA }} --type RUN
-          echo "$(bun input-data --data ${{ env.WIBU_DATA }})" >> $GITHUB_ENV
+          echo "init data ..." | bun notif --data ${{ env.WIBU_DATA }} --type RUN && \
+          echo "$(bun input-data --data ${{ env.WIBU_DATA }})" >> $GITHUB_ENV && \
           echo "init data selesai ..." | bun notif --data ${{ env.WIBU_DATA }} --type SUCCESS
 
       - name: clone
         run: |
-          echo "clone project ..." | bun notif --data ${{ env.WIBU_DATA }} --type RUN
-          git clone https://x-access-token:${{ secrets.WIBU_GIT_TOKEN }}@github.com/bipproduction/${{ env.WIBU_REPO }}.git ${{ env.WIBU_APP_VERSION }} 2>&1 | bun notif --data ${{ env.WIBU_DATA }}  
+          echo "clone project ..." | bun notif --data ${{ env.WIBU_DATA }} --type RUN && \
+          git clone https://x-access-token:${{ secrets.WIBU_GIT_TOKEN }}@github.com/bipproduction/${{ env.WIBU_REPO }}.git ${{ env.WIBU_APP_VERSION }} 2>&1 | bun notif --data ${{ env.WIBU_DATA }}  && \ 
           echo "clone project ..." | bun notif --data ${{ env.WIBU_DATA }} --type SUCCESS
 
       - name: handle env
         working-directory: ${{ env.WIBU_APP_VERSION }}
         run: |
-          echo "handle env ..." | bun notif --data ${{ env.WIBU_DATA }} --type RUN
-          echo "${{ env.WIBU_ENV }}" > .env
+          echo "handle env ..." | bun notif --data ${{ env.WIBU_DATA }} --type RUN && \
+          echo "${{ env.WIBU_ENV }}" > .env && \
           echo "handle env ..." | bun notif --data ${{ env.WIBU_DATA }} --type SUCCESS
 
-      # - name: clone and build
-      #   run: |
-      #     echo "clone and build ..." | bun notif
-      #     bun run build.ts
+      - name: build
+        working-directory: ${{ env.WIBU_APP_VERSION }}
+        run: |
+          echo "build ..." | bun notif --data ${{ env.WIBU_DATA }} --type RUN
+          OUTPUT=$(bun run build 2>&1)
+          EXIT_CODE=$?
+
+          if [ $EXIT_CODE -eq 0 ]; then
+            echo "$OUTPUT" | bun notif --data ${{ env.WIBU_DATA }} --type SUCCESS
+          else
+            echo "$OUTPUT" | bun notif --data ${{ env.WIBU_DATA }} --type ERROR
+            exit $EXIT_CODE
+          fi
 
       # - name: Deploy to VPS (New Version)
       #   uses: appleboy/scp-action@master
